"""add idempotency_key and version to orders

Revision ID: 836e0b129bfd
Revises: bd7e4b32c6d2
Create Date: 2026-09-30 13:11:59.890457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836e0b129bfd'
down_revision: Union[str, Sequence[str], None] = 'bd7e4b32c6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    # server_default backfills existing rows to version=1; dropped right
    # after so future inserts must supply it explicitly (matches the
    # model, which has a Python-side default, not a DB-side one).
    op.add_column('orders', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('orders', 'version', server_default=None)
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_column('orders', 'version')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
